blerg_app/urls.py
from django.urls import path
from . import views

app_name = 'blerg_app' # for namespacing
urlpatterns = [
    path('', views.index, name='index'),
	path('search_blerg/', views.search_blerg, name='search_blerg'),
	path('detail/<int:pk>', views.comment, name='comment'),
	path('edit/<int:pk>', views.edit_comment, name='edit_comment'),
	path('edit_post/<int:pk>', views.edit_post, name='edit_post'),
	path('delete_post/<int:pk>', views.delete_post, name='delete_post'),
	path('delete/<int:pk>', views.delete_comment, name='delete_comment'),
	path('new_post/', views.new_post, name='new_post'),
	path('save_post/<int:pk>', views.save_post, name='save_post'),
	path('save_updated_post/<int:pk>', views.save_updated_post, name='save_updated_post'),
	path('<title>/', views.visit_blerg, name='visit_blerg')#the <title> variable is what gets passed into the views.whatever when you call it. You can put as many variables as you want there (i.e.'<title>/<variable>') as long as there are arguements in the view to recieve the information. The way to access the HTML code is by having the view call it, not by this page. The variables that come through here can be grabbed directly from the nav bar or from input in the html forms


]

blerg_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', include('blerg_app.urls')),
	path('accounts/', include('django.contrib.auth.urls')),
	path('accounts/register/', views.register, name='register'),
]

blerg_app/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User


class BlogPost(models.Model):
	user = models.ForeignKey(User, on_delete='CASCADE')
	title = models.CharField(max_length=250)
	body = models.TextField()
	timestamp = models.DateTimeField(default=datetime.now())

	def __str__(self):
		blog_entry = self.title + "\n" + self.body
		return blog_entry


class Comment(models.Model):
	user = models.ForeignKey(User, on_delete='CASCADE')
	blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
	body = models.TextField()
	timestamp = models.DateTimeField(default=datetime.now())

	def __str__(self):
		comment_entry = self.blogpost.title + "\n" + self.body
		return comment_entry

blerg_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import BlogPost, Comment
from datetime import datetime
from django.contrib.auth.decorators import user_passes_test



def index(request):
	blog_list = BlogPost.objects.all()
	context = {'blog_list': blog_list}
	return render(request, 'blerg_app/index.html', context)


def search_blerg(request):
	if request.method == 'GET':
		print("you called search_book")
		search_query = request.GET['search_box']
		searched_blogs = []
		bodies = Book.objects.filter(body__icontains=search_query)
		titles =Book.objects.filter(title__icontains=search_query)
		comments = Book.objects.filter(comments__body__icontains=search_query)
		searched_blogs.extend(bodies.union(titles, comments))
		# searched_book.append(Book.objects.filter(author=search_query))
		context = {'blog_list': searched_blogs}
		return render(request, 'blog_app/index.html', context)


def visit_blerg(request, title):
	title_to_view = get_object_or_404(BlogPost, title=title)
	comments = Comment.objects.filter(blogpost__title=title)
	print(title_to_view)
	print(comments)
	# return HttpResponse("You went to a blog")
	context = {'title_to_view': title_to_view, 'comments': comments}
	return render(request, 'blerg_app/detail.html', context)


def confirm_commenter(user):
	return user.groups.filter(name='Commenters').exists()


@user_passes_test(confirm_commenter)
def comment(request, pk):
	if request.method == 'POST':
		new_comment = request.POST['new_comment']
		blogpost = get_object_or_404(BlogPost, pk=pk)
		Comment(body=new_comment, user=request.user, blogpost=blogpost).save()
		title = blogpost.title
		print(title)
		return redirect('blerg_app:visit_blerg', title=title)
		return HttpResponse(f'you called the comment function for {new_comment}')


@user_passes_test(confirm_commenter)
def delete_comment(request, pk):
	if request.method == 'GET':
		comment = get_object_or_404(Comment, pk=pk)
		Comment.objects.get(pk=pk).delete()
		title = comment.blogpost.title
		return redirect('blerg_app:visit_blerg', title=title)
		return HttpResponse(f'deleted!')


@user_passes_test(confirm_commenter)
def edit_comment(request, pk):
	if request.method == 'POST':
		updated_comment = request.POST['text_to_change']
		comment = get_object_or_404(Comment, pk=pk)
		comment.body= updated_comment
		comment.save()
		title = comment.blogpost.title
		# return HttpResponse(f'see if that worked... new comment is {updated_comment}!')
		return redirect('blerg_app:visit_blerg', title=title)


def confirm_poster(user):
	return user.groups.filter(name='Posters').exists()


@user_passes_test(confirm_poster)
def new_post(request):
	user = request.user
	timestamp = datetime.now()
	title = ''
	body = ''
	context = {"user": user, "timestamp": timestamp, 'title': title, 'body': body, 'button': 'Create Post', 'url': 'blerg_app:save_post', 'pk': 0}
	return render(request, 'blerg_app/new_post.html', context)
	return HttpResponse(f'go to new post page')


def save_post(request, pk):
	print("save_post")
	if request.method == 'POST':
		body = request.POST['body']
		title = request.POST['title']
		new = BlogPost(body=body, user=request.user, title=title).save()
		print(new)
		return redirect('blerg_app:visit_blerg', title=title)


@user_passes_test(confirm_poster)
def edit_post(request, pk):
	user = request.user
	post = get_object_or_404(BlogPost, pk=pk)
	title = post.title
	body = post.body
	context = {"user": user, 'title': title, 'body': body, 'button': 'Save', 'url': 'blerg_app:save_updated_post', 'pk':pk}
	return render(request, 'blerg_app/new_post.html', context)
	return HttpResponse(f'go edit your shit')
	return HttpResponse(f'see if that worked... new comment is {updated_comment}!')
	# return redirect('blerg_app:visit_blerg', title=title)


def save_updated_post(request, pk):
	if request.method == 'POST':
		post = get_object_or_404(BlogPost, pk=pk)
		post.body = request.POST['body']
		post.title = request.POST['title']
		post.save()
	return redirect('blerg_app:visit_blerg', title=post.title)
	return HttpResponse(f'save')


@user_passes_test(confirm_poster)
def delete_post(request, pk):
	if request.method == 'POST':
		BlogPost.objects.get(pk=pk).delete()
	return redirect('blerg_app:index')
	return HttpResponse(f'save')

blerg_site/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.models import User, Group, Permission
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login


def register(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data['username']
			password = form.clean_password2()
			user = authenticate(username=username, password=password)
			if user:
				login(request, user)
				group = Group.objects.get(name='Commenters')
				user.groups.add(group) #documentation in code guild under user management
			return redirect('blerg_app:index')
		else:
			return HttpResponse('Invalid form')
	context = {'form': UserCreationForm()}
	return render(request, 'registration/register.html', context)

blerg_app/templates/blerg_app/detail.html
{% extends "base_generic.html" %}

{% load static %}
{%  load check_group %}

{% block content %}
<h1> Welcome to the blerg </h1>
<div class="title">
	<h2 class="center">{{title_to_view.title}}</h2>
	<p>By: {{title_to_view.user}}</p>
	<p>Posted: {{title_to_view.timestamp}}</p>
	<pre id="body">{{title_to_view.body}}</pre>
</div>


{% if user.is_authenticated %}
	{% if user|in_Posters_group %}
	<form action="{% url 'blerg_app:edit_post' pk=title_to_view.pk %}" method="get">
		<button name="edit">Edit</button>
	</form>
	<form action="{% url 'blerg_app:delete_post' pk=title_to_view.pk %}" method="post">
		{% csrf_token%}
		<button name="edit">Delete</button>
	</form>
	{%  endif  %}
{%  endif  %}


{% for comment in comments%}
<div class="comment">
	<p id="body"> {{comment.body}} </p></br>
	posted by: {{comment.user}}</br>
		{% if user.is_authenticated %}
			{% if comment.user.username == request.user.username %}
			<form action="{% url 'blerg_app:edit_comment' pk=comment.pk %}" method="post">
				{% csrf_token%}
				<button id="edit_comment" type="button" name="edit">Edit</button>
				<textarea id="text_to_change" name="text_to_change" class="hidden">{{comment.body}}</textarea>
				<button id="submit_changed_comment" class="hidden"  type="submit" name="edit_comment">Update comment</button>
			</form>

			<form action="{% url 'blerg_app:delete_comment' pk=comment.pk %}" method="get">
				<button type="submit" name="delete">Delete</button>
			</form>
			{% endif %}
</div>
		{% endif %}
	{%endfor%}


{% if user.is_authenticated %}
		<form action="{% url 'blerg_app:comment' pk=title_to_view.pk %}" method="post">
			{% csrf_token%}
			Add comment:
				<textarea name="new_comment" placeholder="Comment..."></textarea>
				<button type="submit">Submit</button>
		</form>
{% else %}
		<a href="{% url 'login' %}">Login to comment</a></br>
{% endif %}

<script src={%static 'blerg_app/script.js' %}> </script>

{% endblock %}

blerg_app/templates/blerg_app/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1> Welcome to the blerg </h1>

<form action="{%url 'blerg_app:search_blerg' %}" method="get">
	<input  id="search_box" type="text" name="search_box"  placeholder="Search..." >
	<button id="search_submit" type="submit" >Submit</button>
</form>


{% for post in blog_list %}
		<div class='title'>
			<h3><a href="{% url 'blerg_app:visit_blerg' post.title %}">{{post.title}}</a></h3>
			<p>Author: {{post.user}}</p>
			<p>Date: {{post.timestamp}}
		</div>
{% endfor %}


{% endblock %}

blerg_app/templates/blerg_app/new_post.html
{% extends "base_generic.html" %}

{% load static %}

{% block content %}
<h1> Welcome to the blerg </h1>
<form action="{% url url pk=pk %}" method="post">
	{% csrf_token%}
<h2><input name="title" id="new_title" placeholder="Title..." value='{{title}}'></input></h2>
<h3>By: {{user.username}}</h3>
<!-- <h3>Posted: {{timestamp}}</h3> -->
<p class="border" id='new_body_p'><textarea name="body" id="new_body" placeholder="Blog post...">{{body}}</textarea></p>
<button>{{button}}</button>
</form>


<script src={%static 'blerg_app/script.js' %}> </script>

{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Blerg!</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">



  <!-- Add additional CSS in static file -->


  {% load static %}
	{%  load check_group %}
  {% block stylesheets %}
	<link rel="stylesheet" type="text/css" href="{%static 'style.css' %}"/>
	{% endblock %}
	{% block extrastyles %}{% endblock %}
</head>

<body>
	{% block nav %}
	<nav>
		<h1>Blerg!</h1>
		<ul class="sidebar-nav">
			<a href="{% url 'blerg_app:index' %}">Home</a></br>
			{% if user.is_authenticated %}
				{% if user|in_Posters_group %}
				<a href="{% url 'blerg_app:new_post' %}">Create Post</a></br>
				{% endif %}
				<a href="{% url 'logout' %}">Logout</a></br>
			{% else %}
				<a href="{% url 'register' %}">Register</a></br>
				<a href="{% url 'login' %}">Login</a></br>
				{% endif %}
		</ul>
	</nav>
	{% endblock %}



    {% block sidebar %}{% endblock %}
<div class="content">
{% block content %}{% endblock %}
</div>

</body>
</html>